# I decide to start config my shell env starting from bash. Fish or other shells should be started from bash and inherit its settings.

# config starship
export STARSHIP_CONFIG=~/.config/starship/starship.toml
eval "$(starship init bash)"

# config yazi
function y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  yazi "$@" --cwd-file="$tmp"
  if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
    builtin cd -- "$cwd"
  fi
  rm -f -- "$tmp"
}

# config conda
function init_conda() {
  # >>> conda initialize >>>
  # !! Contents within this block are managed by 'conda init' !!
  __conda_setup="$('/home/aor/softwares/miniconda3/bin/conda' 'shell.bash' 'hook' 2>/dev/null)"
  if [ $? -eq 0 ]; then
    eval "$__conda_setup"
  else
    if [ -f "/home/aor/softwares/miniconda3/etc/profile.d/conda.sh" ]; then
      . "/home/aor/softwares/miniconda3/etc/profile.d/conda.sh"
    else
      export PATH="/home/aor/softwares/miniconda3/bin:$PATH"
    fi
  fi
  unset __conda_setup
  # <<< conda initialize <<<
}

# config cuda
export CUDACXX="/opt/cuda/bin/nvcc"
